steps:
- name: 'gcr.io/$PROJECT_ID/ngcontainer'
  args: ['npm', 'install']
- name: 'gcr.io/$PROJECT_ID/ngcontainer'
  args: ['npm', 'run', 'test:ci']
- name: 'gcr.io/$PROJECT_ID/ngcontainer'
  args: ['npm', 'run', 'build']
- name: 'gcr.io/cloud-builders/docker'
  args: ["build", "-t", "gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA", "."]
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA"]
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment/$PROJECT_ID-staging'
  - 'xlayers=gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-east4-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=xlayers'
images:
  - 'gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/$REPO_NAME:latest'

# steps:
# - name: 'gcr.io/cloud-builders/docker'
#   args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/ngcontainer', '.', '-f', 'Dockerfile_angular' ]
# images:
# - 'gcr.io/$PROJECT_ID/ngcontainer'